schedules:
- cron: "0 0 * * *"
  displayName: Midnight update
  branches:
    include:
    - master

# Disable CI trigger (don't run on commits)
trigger: none
# and don't run on Pull Requests
pr: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: openvino_development
    timeoutInMinutes: 0
    steps:
    - checkout: self
      persistCredentials: true
      clean: true

    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: ~/.ssh/known_hosts
        sshPublicKey: $(public_deploy_key)
        sshKeySecureFile: deploy_key

    - script: docker build -t scoreboard/openvino -f runtimes/openvino/development/Dockerfile .
      displayName: 'Build docker image'

    - script: . setup/git-setup.sh
      displayName: 'Git setup'

    - script: docker run --name openvino --env-file setup/env.list -v `pwd`/results/openvino/development:/root/results scoreboard/openvino || true
      displayName: 'Run docker container'

    - script: . setup/git-deploy-results.sh
      displayName: 'Deploy results'
